# Generated by Django 5.1.6 on 2025-02-18 21:22

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='hospital_app.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='working_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=64),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='doctor',
            field=models.ManyToManyField(related_name='specialty', to='hospital_app.doctorprofile'),
        ),
    ]
