# Generated by Django 5.1.6 on 2025-02-19 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0003_feedback_created_at_alter_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='hospital_app.doctorprofile'),
        ),
    ]
